/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package martinkontsek.gui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import martinkontsek.core.Answer;
import martinkontsek.core.MoodleQuizCreator;
import martinkontsek.core.Question;
import martinkontsek.core.QuestionTypeEnum;

/**
 *
 * @author Martin
 */
public class NewQuestionDialog extends javax.swing.JDialog 
{
    private MoodleQuizCreator aQuizCreator;
    private Question aQuestion;
    private boolean aEditing;
    
    private DefaultTableModel aTableModel;    
    

    /**
     * Creates new form NewQuestionDialog
     */
    public NewQuestionDialog(java.awt.Frame parent, boolean modal, MoodleQuizCreator paQuizCreator, Question paQuestion) {
        super(parent, modal);
        initComponents();
        
        aQuizCreator = paQuizCreator;
        cbQueType.setModel(new DefaultComboBoxModel<>(QuestionTypeEnum.values()));
        aTableModel = (DefaultTableModel) tabAnswers.getModel();
        
        tabAnswers.getTableHeader().setReorderingAllowed(false);
        tabAnswers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabAnswers.getColumnModel().getColumn(1).setMaxWidth(50);
        tabAnswers.getColumnModel().getColumn(1).setResizable(false);
        
        if(paQuestion != null)
        {
            aQuestion = paQuestion;
            aEditing = true;
            
            this.loadValues();
            btnAddQuestion.setText("Save");
            this.setTitle("Edit Question");
        } else {
            aQuestion = new Question();
            aEditing = false;
            
            aTableModel.addRow(new Object[]{"true", false});
            aTableModel.addRow(new Object[]{"false", false});
        }
    }
    
    private void loadValues()
    {
        tfQueName.setText(aQuestion.getQuestionName());
        taQueText.setText(aQuestion.getQuestionText());
        
        for(Answer answer : aQuestion.getAllAnswers())
        {
            aTableModel.addRow(new Object[]{answer.getText(), answer.isRight()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labQueType = new javax.swing.JLabel();
        cbQueType = new javax.swing.JComboBox();
        labQueName = new javax.swing.JLabel();
        tfQueName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taQueText = new javax.swing.JTextArea();
        labQueText = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabAnswers = new javax.swing.JTable();
        btnNewAnswer = new javax.swing.JButton();
        btnAddQuestion = new javax.swing.JButton();
        btnRemoveAnswer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Question");

        labQueType.setText("Question Type:");

        cbQueType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "True/False", "Multichoice" }));

        labQueName.setText("Question Name:");

        taQueText.setColumns(20);
        taQueText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taQueText.setLineWrap(true);
        taQueText.setRows(5);
        taQueText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taQueText);

        labQueText.setText("Question Text:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labQueText)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labQueType)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbQueType, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 256, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labQueName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfQueName)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labQueType)
                    .addComponent(cbQueType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labQueName)
                    .addComponent(tfQueName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labQueText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Answers"));

        tabAnswers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Answer Text", "Correct"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabAnswers);

        btnNewAnswer.setText("+");
        btnNewAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAnswerActionPerformed(evt);
            }
        });

        btnAddQuestion.setText("Add");
        btnAddQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddQuestionActionPerformed(evt);
            }
        });

        btnRemoveAnswer.setText("-");
        btnRemoveAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveAnswerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNewAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnAddQuestion)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddQuestionActionPerformed
        aQuestion.setQuestionType((QuestionTypeEnum)cbQueType.getSelectedItem());
        
        String questionName = tfQueName.getText();
        String questionText = taQueText.getText();
        
        aQuestion.setQuestionName(questionName);
        aQuestion.setQuestionText(questionText);
        
        if(aEditing)
            aQuestion.removeAllAnswers();
        
        for(int i=0; i < aTableModel.getRowCount(); i++)
        {
            String text = (String) aTableModel.getValueAt(i, 0);
            boolean isRight = (boolean) aTableModel.getValueAt(i, 1);
            
            aQuestion.addAnswer(isRight, text);
        }
        
        if(aEditing)
            aQuizCreator.editQuestionCallBack(aQuestion);
        else
            aQuizCreator.addQuestionCallBack(aQuestion);
        
        this.dispose();
    }//GEN-LAST:event_btnAddQuestionActionPerformed

    private void btnNewAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAnswerActionPerformed
        aTableModel.addRow(new Object[]{"", false});
    }//GEN-LAST:event_btnNewAnswerActionPerformed

    private void btnRemoveAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAnswerActionPerformed
        aTableModel.removeRow(tabAnswers.getSelectedRow());
    }//GEN-LAST:event_btnRemoveAnswerActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddQuestion;
    private javax.swing.JButton btnNewAnswer;
    private javax.swing.JButton btnRemoveAnswer;
    private javax.swing.JComboBox cbQueType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labQueName;
    private javax.swing.JLabel labQueText;
    private javax.swing.JLabel labQueType;
    private javax.swing.JTextArea taQueText;
    private javax.swing.JTable tabAnswers;
    private javax.swing.JTextField tfQueName;
    // End of variables declaration//GEN-END:variables
}
